### ISSUE TITLE
Project Licence

### ISSUE THREAD

**Issue by andre-geldenhuis** [carl-tt/led-bar-mesh#1]
Hiya

This is a cool project :)  I was thinking about forking it for a led art project, but I'd prefer not to do that without a licence.

Any chance you would like to add a licence like MIT or GPL or whatever to this project?

**Comment by carl-tt** [comment]
Andre -

Thanks.  I prefer the Non-Commercial license used on Instructables, but I
put the MIT on the GIT repository since it's easier.  Good luck with the
project!

- Carl

**Comment by andre-geldenhuis** [comment]
That's great!  

Much appreciated, and thanks! :)
